### PR TITLE
chore: update ed25519-dalek to v2.1.1

### PR DESCRIPTION
**Pull request by koushiro**
Close #94

### CODE REVIEW

**Review by dmitry-markin — APPROVED** [review]
Hey! Thanks for contributing! This will require minor updates in polkadot-sdk due to public API changes, but I can handle it after releasing these changes in litep2p.

**Comment by dmitry-markin** [comment]
@koushiro As the CI error says, would it be possible for you to sign the commit with your GutHub GPG key?

**Review by lexnv — APPROVED** [review]
LGTM! Thanks for contributing! 🙏

**Comment by dmitry-markin** [comment]
Thanks again for contributing, and sorry that merging this took quite some time. We are going to reconsider requiring signed commits from external contributors.

**Pull request merged**
